In [3]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [7]:
np.sum(x)

10

In [10]:
np.sum(x,axis=0)
np.sum(x,axis=1)

array([3, 7])

In [14]:
x = np.array([[1,2],[3,4],[5,6]])
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
x.T

array([[1, 3, 5],
       [2, 4, 6]])

In [24]:
v= np.array([[1,2,3]])
print(v)
v.shape

[[1 2 3]]


(1, 3)

In [27]:
v.T

array([[1],
       [2],
       [3]])

In [31]:
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v,(3,1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [33]:
x = np.array([[1,2,3],[4,5,6]])
print(x+v)

[[2 4 6]
 [5 7 9]]


In [35]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
w

array([4, 5])

In [38]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [40]:
print(x*np.reshape(w,(2,1)))

[[ 4  8 12]
 [20 25 30]]


In [47]:
#Scipy
# Provides large number of number of functions that operates on numpy arrays and useful for different scientific and engineering application

from scipy.misc import imread,imresize,imsave,imshow

img = imread('test.jpg')

print(img.dtype)

print(img.shape)



img_tinted = img*[1,0.95,0.9]

img_tinted = imresize(img_tinted,(300,300))

imsave('test1.jpg',img_tinted)




uint8
(450, 600, 3)


In [57]:
#Matplot Lib

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0,3*np.pi,0.1)
print (x)
y = np.cos(x)
print(y)

plt.plot(x,y)
plt.show()

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4
  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4
  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9
  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4
  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9
  9.   9.1  9.2  9.3  9.4]
[ 1.          0.99500417  0.98006658  0.95533649  0.92106099  0.87758256
  0.82533561  0.76484219  0.69670671  0.62160997  0.54030231  0.45359612
  0.36235775  0.26749883  0.16996714  0.0707372  -0.02919952 -0.12884449
 -0.22720209 -0.32328957 -0.41614684 -0.5048461  -0.58850112 -0.66627602
 -0.73739372 -0.80114362 -0.85688875 -0.90407214 -0.94222234 -0.97095817
 -0.9899925  -0.99913515 -0.99829478 -0.98747977 -0.96679819 -0.93645669
 -0.89675842 -0.84810003 -0.79096771 -0.7259323  -0.65364362 -0.57482395
 -0.49

In [58]:
plt.imshow(np.uint8(img_tinted))
plt.show()