In [2]:
#Hih performance multidimensional array object

import numpy as np

a = np.array([1,2,3])

print(a)


[1 2 3]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape)

(3,)


In [9]:
print(a[0],a[1])

1 2


In [11]:
a[0] = 5

In [13]:
print(a)

[5 2 3]


In [14]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
print(type(b))

<class 'numpy.ndarray'>


In [18]:
print(b.shape)

(2, 3)


In [20]:
print(b[0,0],b[0,1])

1 2


In [21]:
#Functions to create arrays

a = np.zeros((3,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [22]:
a = np.ones((2,3))
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [24]:
a = np.full((3,3),6)
print(a)

[[ 6.  6.  6.]
 [ 6.  6.  6.]
 [ 6.  6.  6.]]


/Users/mnoordeen/anaconda/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((3, 3), 6) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [27]:
a = np.eye(5)
print(a)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [41]:
a = np.random.random((2,2))
print(a)

[[ 0.41252983  0.1130993 ]
 [ 0.9614972   0.0067001 ]]


In [48]:
#Array indexing - Slicing

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

print(a[1,1:3]) # 1 -> row , 1:3 => column

# 1:3 -> starts from 2 column end till 3rd column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[6 7]


In [52]:
print(a[0:,:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [54]:
print(a[0,1])
a[0,1] = 77
print(a)

2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
row_r1 = a[1,:]   # ->  Rank 1 view of second row of a
print(row_r1)

[5 6 7 8]


In [63]:
row_r2 = a[1:2,:]   # ->  Rank 2 view of second row of a
print(row_r2)

[[5 6 7 8]]


In [60]:
print(row_r1.shape)


(4,)


In [61]:
print(row_r2.shape)


(1, 4)


In [64]:
a[:,1]

array([77,  6, 10])

In [65]:
a[:,1:2]

array([[77],
       [ 6],
       [10]])

In [74]:
#Integer array index

a = np.array([[1,2],[3,4],[5,6]])

print (a)

print(a.shape)

#print(a[[0,1,2],[0,1,0]])

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [75]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [76]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
#Datatype
x = np.array([1,2])
x.dtype

dtype('int64')

In [79]:
x = np.array([1.,2])
x.dtype

dtype('float64')

In [81]:
x = np.array([True,False])
x.dtype

dtype('bool')

In [82]:
np.array([1,2],dtype=np.float64)

array([ 1.,  2.])

In [91]:
#Array Math

x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype = np.float64)
print("x = ",x)
print("y = ",y)

x =  [[ 1.  2.]
 [ 3.  4.]]
y =  [[ 5.  6.]
 [ 7.  8.]]


In [86]:
print(x+y)

[[  6.   8.]
 [ 10.  12.]]


In [88]:
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]


In [89]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [90]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [92]:
print(x*y)

[[  5.  12.]
 [ 21.  32.]]


In [93]:
print(np.multiply(x,y))

[[  5.  12.]
 [ 21.  32.]]


In [94]:
np.divide(x,y)

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [95]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [96]:
print(x.dot(y))

[[ 19.  22.]
 [ 43.  50.]]


In [97]:
np.dot(x,y)

array([[ 19.,  22.],
       [ 43.,  50.]])